image_gallery/image_gallery/urls.py
from django.urls import path, re_path
from django.contrib.auth import views
from django.views.generic.base import RedirectView

from django.conf import settings
from django.conf.urls.static import static

import image_gallery_app.forms as form
import image_gallery_app.views as view

from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', view.custom_login, name='login'),
    path('accounts/signup/', view.custom_signup, name='signup'),
    path('logout/', view.logout_view, name='logout'),
    path('blog/', view.blog_view, name='blog'),
    path('blog/<slug:slug>/', view.blog_detail, name='blog_detail'),
    path('create_album/', view.create_album_view, name='create_album'),
    path('favourites/', view.favorites_view, name='favourites'),
    path('favorite/<str:item_type>/<int:item_id>/', view.toggle_favorite, name='toggle_favorite'),
    path('feedback-success/', view.feedback_success, name='feedback_success'),  # Success page URL
    path('toggle-favorite/image/<int:image_id>/', view.toggle_favorite_image, name='toggle_favorite_image'),

    path('', view.gallery, name='gallery'),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/icons/favicon.ico', permanent=True)),

    # Keep this last!
    path('albums/<slug:slug>/', view.AlbumDetail.as_view(), name='album'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'image_gallery_app.views.handler404'

image_gallery/image_gallery_app/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
import uuid
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.apps import apps
from datetime import datetime

class Album(models.Model):
    title = models.CharField(max_length=70)
    description = models.TextField(max_length=1024)
    thumb = ProcessedImageField(upload_to='albums', processors=[ResizeToFit(300)], format='JPEG', options={'quality': 90})
    tags = models.CharField(max_length=250)
    is_visible = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=50, unique=True, editable=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            # Save first without slug to get an ID if needed
            super().save(*args, **kwargs)
            self.slug = self.generate_unique_slug()
        self.is_visible = True
        self.modified = datetime.now()
        super().save(*args, **kwargs)

    def generate_unique_slug(self):
        base_slug = slugify(self.title)
        if not base_slug:  # If title is empty or doesn't slugify well
            base_slug = "album"
        unique_slug = f"{base_slug}-{uuid.uuid4().hex[:6]}"
        return unique_slug[:50]

    def average_rating(self):
        ratings = self.ratings.all()
        if ratings:
            return sum(r.rating for r in ratings) / len(ratings)
        return 0

    def __unicode__(self):
        return self.title
    
class AlbumRating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='ratings')
    rating = models.PositiveSmallIntegerField()  # 1 to 5 stars

    class Meta:
        unique_together = ('user', 'album')  # One rating per user per album

class AlbumImage(models.Model):
    image = ProcessedImageField(upload_to='albums', processors=[ResizeToFit(1280)], format='JPEG', options={'quality': 70})
    thumb = ProcessedImageField(upload_to='albums', processors=[ResizeToFit(300)], format='JPEG', options={'quality': 80})
    album = models.ForeignKey('album', on_delete=models.PROTECT)
    alt = models.CharField(max_length=255, default=uuid.uuid4)
    created = models.DateTimeField(auto_now_add=True)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    slug = models.SlugField(max_length=70, default=uuid.uuid4, editable=False)

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback from {self.name}"
    
class Blog(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True, max_length=120, blank=True)  # <-- make it optional in forms    author = models.CharField(max_length=80)
    content = models.TextField()
    author = models.CharField(max_length=80, blank=True, null=True)
    image = ProcessedImageField(upload_to='blogs', processors=[ResizeToFit(800)], format='JPEG', options={'quality': 85})
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 1
            while Blog.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)


def get_default_content_type():
    # Logic to get a default ContentType
    return ContentType.objects.get_for_model(apps.get_model('image_gallery_app.Album')).id

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=get_default_content_type)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')

class FavoriteImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(AlbumImage, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'image')  # Prevent duplicates

image_gallery/image_gallery_app/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*- 
from django import forms
from image_gallery_app.models import Album, Feedback
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class AlbumForm(forms.ModelForm):
    zip = forms.FileField(required=False, help_text="Optional .zip file of images to add to this album")
    class Meta:
        model = Album
        exclude = ['slug', 'created', 'modified']

class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', "message"]
        widgets = {
    'message': forms.Textarea(attrs={'class': 'message-box'})
}
        

class AlbumRatingForm(forms.Form):
    rating = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 6)],
        widget=forms.RadioSelect
    )

image_gallery/image_gallery_app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
import os
import zipfile
import uuid
from io import BytesIO
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpRequest, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate,get_user
from image_gallery_app.models import Album, AlbumImage ,AlbumRating, FavoriteImage
from .forms import SignupForm, LoginForm, FeedbackForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.core.files.base import ContentFile
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.mixins import LoginRequiredMixin


from PIL import Image

from .forms import AlbumForm

from image_gallery_app.models import Album, AlbumImage, Blog, Favorite


def logout_view(request):
    logout(request)
    return redirect('/')

def gallery(request):
    # Fetch albums where is_visible is True, ordered by 'created' in descending order
    albums_list = Album.objects.filter(is_visible=True).order_by('-created')
    print(f"Found {albums_list.count()} visible albums")  # Debug line
    user_favorites = []

    if request.user.is_authenticated:
        album_type = ContentType.objects.get_for_model(Album)
        user_favorites = Favorite.objects.filter(
            user=request.user,
            content_type=album_type
        ).values_list('object_id', flat=True)

    # Set up pagination: 10 albums per page
    paginator = Paginator(albums_list, 10)
    page = request.GET.get('page')
    
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1)  # If page is not an integer, deliver first page.
    except EmptyPage:
        albums = paginator.page(paginator.num_pages)  # If page is out of range, deliver last page of results.

    # Handle form submission (POST)
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save() 
            # Optionally, save the form data to a model or send an email
            # Redirect to the feedback success page after form submission
            return redirect('feedback_success')  # Redirect to the success page

    else:
        form = FeedbackForm()  # Display an empty form on GET request

    # Render the gallery template with albums and form context
    return render(request, 'gallery.html', {
        'albums': albums,
        'form': form,
        'user_favorites': user_favorites
    })


class AlbumDetail(LoginRequiredMixin, DetailView):
    model = Album
    template_name = 'image_gallery_app/album_detail.html'
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        album = self.get_object()

        # Images
        context['images'] = AlbumImage.objects.filter(album=album)

        # Feedback Form
        context['form'] = FeedbackForm()

        # User Rating
        user = self.request.user
        user_rating = None
        if user.is_authenticated:
            user_rating = AlbumRating.objects.filter(user=user, album=album).first()
            favorite_image_ids = FavoriteImage.objects.filter(
                user=self.request.user,
                image__in=album.albumimage_set.all()
            ).values_list('image_id', flat=True)
            context['favorite_image_ids'] = set(favorite_image_ids)
        context['user_rating'] = user_rating

        # Average Rating
        context['average_rating'] = album.average_rating()
        context["rating_range"] = [5, 4, 3, 2, 1]

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'rating' in request.POST:
            # Star rating form submitted
            rating = int(request.POST.get('rating'))
            AlbumRating.objects.update_or_create(
                user=request.user,
                album=self.object,
                defaults={'rating': rating}
            )
            return redirect(self.request.path_info)  # refresh page
        if 'favorite_image' in request.POST:
            image_id = request.POST.get('favorite_image')
            try:
                image = AlbumImage.objects.get(id=image_id)
                fav, created = FavoriteImage.objects.get_or_create(
                    user=request.user,
                    image=image
                )
                if not created:
                    fav.delete()
                return JsonResponse({'status': 'success'})
            except AlbumImage.DoesNotExist:
                return JsonResponse({'status': 'error'}, status=404)

        else:
            # Feedback form submitted
            form = FeedbackForm(request.POST)
            if form.is_valid():
                form.save() 
                # Save or process the feedback as needed
                return redirect('feedback_success')
            
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)
     
def custom_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')  # Redirect to homepage or dashboard
        else:
            print("form invalid******************************************************************************************")
            print("Form errors:", form.errors)
    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form})

def custom_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

def feedback_success(request):
    return render(request, 'feedback/feedback_success.html') 

def handler404(request, exception):
    assert isinstance(request, HttpRequest)
    return render(request, 'handler404.html', None, None, 404)



@login_required
def create_album_view(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                album = form.save(commit=False)
                album.save()  # This triggers the slug generation
                
                if zip_file := form.cleaned_data.get('zip'):
                    try:
                        with zipfile.ZipFile(zip_file) as archive:
                            for entry in sorted(archive.namelist()):
                                if entry.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')):
                                    file_data = archive.read(entry)
                                    filename = os.path.basename(entry)
                                    
                                    with BytesIO(file_data) as buffer:
                                        img = AlbumImage(album=album, alt=filename)
                                        img.image.save(filename, ContentFile(file_data))
                                        
                                        image = Image.open(buffer)
                                        img.width, img.height = image.size
                                        
                                        thumb_buffer = BytesIO()
                                        image.thumbnail((300, 300))
                                        image.save(thumb_buffer, format='JPEG', quality=90)
                                        img.thumb.save(f"thumb_{filename}", ContentFile(thumb_buffer.getvalue()))
                                        img.save()
                    except zipfile.BadZipFile:
                        messages.error(request, "Invalid ZIP file")
                        return redirect('create_album')

                return redirect('album', slug=album.slug)
            
            except Exception as e:
                messages.error(request, f"Error creating album: {str(e)}")
                return redirect('create_album')
    else:
        form = AlbumForm()
    return render(request, 'create_album.html', {'form': form})
from .models import Blog

def blog_view(request):
    blogs = Blog.objects.all()

    user_favorites = []
    if request.user.is_authenticated:
        blog_type = ContentType.objects.get_for_model(Blog)
        user_favorites = Favorite.objects.filter(
            user=request.user,
            content_type=blog_type
        ).values_list('object_id', flat=True)  # returns list of favorited blog IDs

    # Handle form submission (POST)
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save() 
            # Optionally, save the form data to a model or send an email
            # Redirect to the feedback success page after form submission
            return redirect('feedback_success')  # Redirect to the success page

    else:
        form = FeedbackForm()  # Display an empty form on GET request
    return render(request, 'blog.html', {'blogs': blogs,"form":form,'user_favorites': user_favorites})


@login_required
def toggle_favorite(request, item_type, item_id):
    # Map string to model
    model_map = {

image_gallery/image_gallery_app/templates/blog.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
<style>
  .blog-container {
    max-width: 1200px;
    margin: 40px auto;
    padding: 0 20px;
  }

  .blog-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 30px;
  }

  .blog-post {
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
    overflow: hidden;
    display: flex;
    flex-direction: column;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    position: relative;
  }

  .blog-post:hover {
    transform: translateY(-6px);
    box-shadow: 0 8px 20px rgba(0,0,0,0.15);
  }

  .blog-post img {
    width: 100%;
    height: 220px;
    object-fit: cover;
    transition: transform 0.4s ease;
  }

  .blog-post:hover img {
    transform: scale(1.05);
  }

  .blog-post-content {
    padding: 20px;
    flex-grow: 1;
    display: flex;
    flex-direction: column;
  }

  .blog-post h2 {
    margin: 0 0 8px;
    font-size: 22px;
    color: #222;
    transition: color 0.3s ease;
  }

  .blog-post:hover h2 {
    color: #007bff;
  }

  .blog-post small {
    color: #777;
    margin-bottom: 12px;
    display: block;
  }

  .blog-post p {
    color: whitesmoke;
    line-height: 1.6;
    margin-bottom: auto;
  }

  .blog-post a {
    text-align: right;
    color: #007bff;
    font-weight: bold;
    margin-top: 15px;
    text-decoration: none;
    transition: color 0.3s ease;
  }

  .blog-post a:hover {
    color: #0056b3;
    text-decoration: underline;
  }

  .card-action {
    margin-top: 20px;
  }

  .fav-btn {
    background: none;
    border: none;
    color: #e63946;
    font-size: 24px;
    cursor: pointer;
    padding: 0;
    transition: transform 0.2s ease;
  }

  .fav-btn:hover {
    transform: scale(1.1);
  }
</style>

<div class="blog-container">
  <h1 style="text-align:center; margin-bottom: 40px; color: white;">Latest Blog Posts</h1>
  <div class="blog-grid">
    {% for blog in blogs %}
      <div class="blog-post">
        <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
        <div class="blog-post-content">
          <h2>{{ blog.title }}</h2>
          <small>By {{ blog.author }} | {{ blog.created|date:"F j, Y" }}</small>
          <p style="color: black;">{{ blog.content|truncatewords:30 }}</p>
          <div class="card-action" style="display: flex; justify-content: space-between; align-items: center;">
            <a href="{% url 'blog_detail' blog.slug %}">Read More</a>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'toggle_favorite' 'blog' blog.id %}" style="margin: 0;">
              {% csrf_token %}
              <button type="submit" class="fav-btn">
                {% if blog.id in user_favorites %}
                  <i class="fas fa-heart"></i>
                {% else %}
                  <i class="far fa-heart"></i>
                {% endif %}
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    {% empty %}
      <p style="color: whitesmoke;text-align: center;">No blog posts found.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

image_gallery/image_gallery_app/templates/blog_detail.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<div class="container" style="max-width: 800px; margin: 40px auto;">

  <div class="card" style="border-radius: 15px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">

    <img src="{{ blog.image.url }}" alt="{{ blog.title }}" style="width: 100%; object-fit: cover; max-height: 400px;">

    <div class="card-content" style="padding: 20px;">

      <h2 style="margin-top: 0;">{{ blog.title }}</h2>

      <p style="color: #777; margin-bottom: 10px;">By {{ blog.author }} | {{ blog.created|date:"F d, Y" }}</p>

      <div style="line-height: 1.6; font-size: 18px;">
        
        {{ blog.content|linebreaks }}
      </div>
    </div>
  </div>
</div>
{% endblock %}

image_gallery/image_gallery_app/templates/create_album.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<style>
  .form-container {
    width: 55%;
    margin: 40px auto;
    padding: 30px;
    background: #f7f7f7;
    border-radius: 12px;
    box-shadow: 0 2px 12px rgba(0,0,0,0.1);
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    font-weight: bold;
    display: block;
    margin-bottom: 6px;
  }

  input[type="text"],
  textarea,
  input[type="file"] {
    width: 100%;
    padding: 10px;
    font-size: 16px;
    border: 1px solid #ccc;
    border-radius: 8px;
  }

  textarea {
    resize: vertical;
    min-height: 100px;
  }

  .submit-btn {
    padding: 12px 20px;
    background-color: #222;
    color: white;
    font-weight: bold;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .submit-btn:hover {
    background-color: #444;
  }
</style>

<div class="form-container">
  <h2>Create New Album</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
      <label for="id_title">Title</label>
      {{ form.title }}
    </div>

    <div class="form-group">
      <label for="id_description">Description</label>
      {{ form.description }}
    </div>

    <div class="form-group">
      <label for="id_tags">Tags</label>
      {{ form.tags }}
    </div>

    <div class="form-group">
      <label for="id_thumb">Thumbnail</label>
      {{ form.thumb }}
    </div>

    <div class="form-group">
      <label for="id_zip">ZIP file (images)</label>
      {{ form.zip }}
    </div>

    <button type="submit" class="submit-btn">Create Album</button>
  </form>
</div>
{% endblock %}

{% block feedback_form %}{% endblock feedback_form %}

image_gallery/image_gallery_app/templates/handler404.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col s12 m6">
            <h1 class="heading">Page not found.</h1>
            <a href="{% url 'gallery' %}" class="waves-effect waves-light btn btn-large">Back to home</a>
        </div>
    </div>
</div>

{% endblock %}

image_gallery/image_gallery_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% load static %} {% include 'material/includes/material_css.html' %}
    <link rel="stylesheet" href="{% static 'site.css' %}" type="text/css" /> {% block css %}{% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    {% block looks %}{% endblock looks %}
    <style>
        body {
            background-color: #eef2f3;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .form-container {
            width: 800px;
            margin: 100px auto;
            padding: 30px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #333;
            font-size: 26px;
            margin-bottom: 20px;
        }

        label {
            font-size: 16px;
            color: #444;
            display: block;
            margin-top: 15px;
        }

        input, textarea {
            width: 100%;
            padding: 10px;
            font-size: 14px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .errorlist {
            color: red;
            font-size: 13px;
            margin-top: 5px;
        }

        button {
            margin-top: 20px;
            width: 100%;
            padding: 12px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .form-input {
        width: 100%;
        padding: 10px;
        font-size: 14px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .message-box {
        height: 200px;
        resize: vertical; /* optional */
    }

    .submit-btn {
        padding: 12px 20px;
        background-color: #222;
        color: white;
        font-weight: bold;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        transition: background-color 0.3s;
      }
    
      .submit-btn:hover {
        background-color: #444;
      }

    </style>
</head>

<body style="background-color: rgb(27, 26, 26);display: flex;flex-direction: column;">
    <nav style="height:100px;background-color: rgb(27, 26, 26);"role="navigation">
        <div style="display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 20px;
    background-color:rgb(27, 26, 26);
    font-weight: bold;
    color: white;
">
    {% if user.is_authenticated %}
      <span style="font-size: 30px;">Hello {{ user.username }}</span>
      <div style="display: flex; gap: 45px; align-items: center;">
        <a href="{% url 'gallery' %}" style="text-decoration: none; color: white; font-size: 18px;">Gallery</a>
        <a href="{% url 'blog' %}" style="text-decoration: none; color: white; font-size: 18px;">Blog</a>
        <a href="{% url 'favourites' %}" style="text-decoration: none; color: white; font-size: 18px;">Favourites</a>
        <a href="{% url 'create_album' %}" style="text-decoration: none; color: white; font-size: 18px;">Create</a>
        <a href="{% url 'logout' %}" style="text-decoration: none; color: rgb(255, 0, 0); font-size: 18px;">Logout</a>
      </div>
    {% else %}
      <span style="font-size: 30px;">Welcome!</span>
      <div style="display: flex; gap: 10px;">
        <a href="{% url 'login' %}" style="text-decoration: none; color: white; font-size: 18px;">Login</a>
        <span style="color: white;">|</span>
        <a href="{% url 'signup' %}" style="text-decoration: none; color: white; font-size: 18px;">Sign Up</a>
      </div>
    {% endif %}
</div>
        {% block navbar %}
        
        
        {% endblock navbar %}
    </nav>

    {% block content %}{% endblock content %}
    <br>
    {% block feedback_form %}
    <div class="form-container">
        <h2>Leave us your feedback</h2>
        <form method="post">
            {% csrf_token %}
    
            <div>
                <label for="id_name">Name:</label>
                {{ form.name }}
                {% if form.name.errors %}
                    <div class="errorlist">{{ form.name.errors }}</div>
                {% endif %}
            </div>
    
            <div>
                <label for="id_email">Email:</label>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="errorlist">{{ form.email.errors }}</div>
                {% endif %}
            </div>
    
            <div>
                <label for="id_message">Message:</label>
                {{ form.message }}
                {% if form.message.errors %}
                    <div class="errorlist">{{ form.message.errors }}</div>
                {% endif %}
            </div>
    
            <button type="submit" class = "submit-btn">Submit</button>
        </form>
    </div>
    {% endblock feedback_form %}

    <footer class="page-footer darken-3" style="padding: 20px 0; color: #ccc;background-color: rgb(27, 26, 26);">
        <div class="container">
          <div class="row">
            <div class="col s12 m6">
              <h6 style="margin-bottom: 10px; font-weight: bold;">About Us</h6>
              <p style="font-size: 0.9rem; line-height: 1.5;">
                GalleryApp is a minimalist photo sharing platform crafted for creators. We believe in simplicity, speed, and stunning image experiences.
              </p>
            </div>
            <div class="col s12 m6 right-align">
              <p style="font-size: 0.8rem;">&copy; 2025 GalleryApp. All rights reserved.</p>
            </div>
          </div>
        </div>
      </footer>

    <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script> -->
    {% include 'material/includes/material_js.html' %}
    <script src="{% static 'app.js' %}"></script> {% block js %}{% endblock %}
</body>

</html>